     
  
   const dati = {
    "Verbo ESSERE. Presente indicativo":{ 
        descrizione: "Es: Tu ___ alto. => Tu SEI alto.",
        domande: [
        { frase: "Luca ___ allegro", corretta: ["è"], risposte: ["sei", "sono", "è", "siete"] },
  { frase: "Giulia ___ simpatica", corretta: ["è"], risposte: ["e", "è", "sono", "siete"] },
  { frase: "Marco ___ gentile", corretta: ["è"], risposte: ["è", "e", "sono", "siete"] },
  { frase: "Io e te ___ in classe", corretta: ["siamo"], risposte: ["siamo", "sono", "siete", "è"] },
  { frase: "Tu e Marco ___ puntuali", corretta: ["siete"], risposte: ["siete", "siamo", "sono", "è"] },
  { frase: "Marco e Giulia ___ stanchi", corretta: ["sono"], risposte: ["sono", "sei", "è", "siamo"] },
  { frase: "Francesco ___ arrabbiato", corretta: ["è"], risposte: ["e", "sono", "è", "siete"] },
  { frase: "Marta ___ emozionata", corretta: ["è"], risposte: ["è", "e", "sono", "siete"] },
  { frase: "Davide ___ silenzioso", corretta: ["è"], risposte: ["è", "e", "sono", "siete"] },
  { frase: "Maria ___ curiosa", corretta: ["è"], risposte: ["è", "e", "sono", "siete"] },
  { frase: "Io e Anna ___ motivati", corretta: ["siamo"], risposte: ["siamo", "sono", "siete", "è"] },
  { frase: "Tu e Paolo ___ distratti", corretta: ["siete"], risposte: ["siete", "sono", "siamo", "è"] },
  { frase: "I bambini ___ vivaci", corretta: ["sono"], risposte: ["sono", "siete", "è", "siamo"] },
  { frase: "Luca ___ in cucina", corretta: ["è"], risposte: ["è", "sei", "sono", "e"] },
  { frase: "Laura ___ in ufficio", corretta: ["è"], risposte: ["è", "e", "sono", "siamo"] },
  { frase: "Marco ___ in palestra", corretta: ["è"], risposte: ["è", "sono", "siete", "siamo"] },
  { frase: "Chiara ___ in montagna", corretta: ["è"], risposte: ["è", "e", "sono", "siamo"] },
  { frase: "Io e te ___ colleghi", corretta: ["siamo"], risposte: ["siamo", "siete", "sono", "è"] },
  { frase: "Tu e Anna ___ nervosi", corretta: ["siete"], risposte: ["siete", "siamo", "sono", "è"] },
  { frase: "Giulia e Paolo ___ a scuola", corretta: ["sono"], risposte: ["sono", "siete", "è", "siamo"] },
  { frase: "Franco ___ tranquillo", corretta: ["è"], risposte: ["è", "e", "sono", "siete"] },
  { frase: "Andrea ___ generoso", corretta: ["è"], risposte: ["è", "e", "sono", "siete"] },
  { frase: "Giovanni ___ simpatico", corretta: ["è"], risposte: ["è", "sono", "sei", "siete"] },
  { frase: "Silvia ___ famosa", corretta: ["è"], risposte: ["è", "sono", "e", "siete"] },
  { frase: "Io e Giovanni ___ soddisfatti", corretta: ["siamo"], risposte: ["siamo", "siete", "sono", "è"] },
  { frase: "Tu e Luca ___ affamati", corretta: ["siete"], risposte: ["siete", "siamo", "sono", "è"] },
  { frase: "I ragazzi ___ educati", corretta: ["sono"], risposte: ["sono", "sei", "siete", "siamo"] },
      { frase: "Io ___ felice", corretta: ["sono"], risposte: ["sei", "sono", "è", "siete"] },
      { frase: "Tu ___ italiano", corretta: ["sei"], risposte: ["sono", "sei", "è", "siete"] },
      { frase: "Lui ___ alto", corretta: ["è"], risposte: ["sono", "sei", "è", "siete"] },
      { frase: "Noi ___ studenti", corretta: ["siamo"], risposte: ["siamo", "siete", "sono", "è"] },
      { frase: "Voi ___ simpatici", corretta: ["siete"], risposte: ["sei", "siete", "sono", "è"] },
      { frase: "Loro ___ felici", corretta: ["sono"], risposte: ["siete", "è", "sono", "siamo"] },
      { frase: "Io ___ stanco", corretta: ["sono"], risposte: ["sei", "sono", "è", "siete"] },
      { frase: "Tu ___ felice", corretta: ["sei"], risposte: ["sono", "sei", "è", "siete"] },
      { frase: "Lui ___ intelligente", corretta: ["è"], risposte: ["sono", "e", "è", "siamo"] },
      { frase: "Lei ___ gentile", corretta: ["è"], risposte: ["è", "sono", "sei", "siete"] },
      { frase: "Noi ___ pronti", corretta: ["siamo"], risposte: ["siamo", "siete", "sono", "è"] },
      { frase: "Voi ___ occupati", corretta: ["siete"], risposte: ["siete", "siamo", "sono", "è"] },
      { frase: "Loro ___ malati", corretta: ["sono"], risposte: ["sono", "sei", "siete", "siamo"] },
      { frase: "Io ___ a casa", corretta: ["sono"], risposte: ["sono", "sei", "è", "siete"] },
      { frase: "Tu ___ al lavoro", corretta: ["sei"], risposte: ["sei", "sono", "è", "siamo"] },
      { frase: "Lui ___ in ritardo", corretta: ["è"], risposte: ["è", "sono", "siamo", "siete"] },
      { frase: "Lei ___ in vacanza", corretta: ["è"], risposte: ["è", "sono", "sei", "siamo"] },
      { frase: "Noi ___ amici", corretta: ["siamo"], risposte: ["siamo", "siete", "sono", "è"] },
      { frase: "Voi ___ pronti", corretta: ["siete"], risposte: ["siete", "siamo", "sono", "è"] },
      { frase: "Loro ___ occupati", corretta: ["sono"], risposte: ["sono", "sei", "siete", "siamo"] },
      { frase: "Io ___ contento", corretta: ["sono"], risposte: ["sono", "sei", "è", "siete"] },
      { frase: "Tu ___ coraggioso", corretta: ["sei"], risposte: ["sei", "sono", "è", "siete"] },
      { frase: "Lui ___ in gamba", corretta: ["è"], risposte: ["è", "sono", "e", "siamo"] },
      { frase: "Lei ___ ricca", corretta: ["è"], risposte: ["è", "sono", "sei", "siete"] },
      { frase: "Noi ___ stanchi", corretta: ["siamo"], risposte: ["siamo", "siete", "sono", "è"] },
      { frase: "Voi ___ felici", corretta: ["siete"], risposte: ["siete", "siamo", "sono", "è"] },
      { frase: "Loro ___ intelligenti", corretta: ["sono"], risposte: ["sono", "sei", "siete", "siamo"] }

    ]
    },
    "Verbo Avere. Presente indicativo": {
       descrizione: "Noi ___ fretta. => Noi ABBIAMO fretta.",
       domande:[
          { frase: "Luca ___ un appartamento", corretta: ["ha"], risposte: ["hai", "ho", "ha", "hanno"] },
  { frase: "Giulia ___ un gatto", corretta: ["ha"], risposte: ["ha", "ho", "hai", "hanno"] },
  { frase: "Marco ___ una bicicletta", corretta: ["ha"], risposte: ["ha", "hai", "ho", "hanno"] },
  { frase: "Io e te ___ una figlia", corretta: ["abbiamo"], risposte: ["abbiamo", "avete", "hanno", "ho"] },
  { frase: "Tu e Marco ___ un appuntamento", corretta: ["avete"], risposte: ["avete", "abbiamo", "hanno", "ha"] },
  { frase: "Luca e Anna ___ fame", corretta: ["hanno"], risposte: ["ha", "hanno", "abbiamo", "hai"] },
  { frase: "Francesca ___ sonno", corretta: ["ha"], risposte: ["ha", "ho", "hanno", "hai"] },
  { frase: "Matteo ___ torto", corretta: ["ha"], risposte: ["ha", "hai", "ho", "hanno"] },
  { frase: "Davide ___ paura del buio", corretta: ["ha"], risposte: ["ha", "hai", "ho", "hanno"] },
  { frase: "Silvia ___ molta sete", corretta: ["ha"], risposte: ["ha", "hanno", "ho", "hai"] },
  { frase: "Io e Marco ___ fretta", corretta: ["abbiamo"], risposte: ["abbiamo", "hanno", "avete", "ho"] },
  { frase: "Tu e Giulia ___ pazienza", corretta: ["avete"], risposte: ["avete", "abbiamo", "hanno", "ho"] },
  { frase: "I ragazzi ___ compiti da fare", corretta: ["hanno"], risposte: ["hanno", "ha", "abbiamo", "avete"] },
  { frase: "Fabio ___ una proposta", corretta: ["ha"], risposte: ["ho", "ha", "hanno", "avete"] },
  { frase: "Chiara ___ un desiderio", corretta: ["ha"], risposte: ["ha", "hai", "hanno", "ho"] },
  { frase: "Andrea ___ una domanda", corretta: ["ha"], risposte: ["ha", "hanno", "ho", "hai"] },
  { frase: "Sofia ___ un dubbio", corretta: ["ha"], risposte: ["ha", "ho", "hanno", "hai"] },
  { frase: "Io e Giulia ___ una casa nuova", corretta: ["abbiamo"], risposte: ["abbiamo", "avete", "hanno", "ho"] },
  { frase: "Tu e Paolo ___ una proposta interessante", corretta: ["avete"], risposte: ["avete", "abbiamo", "hanno", "ha"] },
  { frase: "Luca e Marta ___ un progetto ambizioso", corretta: ["hanno"], risposte: ["hanno", "ha", "abbiamo", "avete"] },
  { frase: "Marta ___ un segreto da raccontare", corretta: ["ha"], risposte: ["ha", "ho", "hai", "hanno"] },
  { frase: "Simone ___ un biglietto per il concerto", corretta: ["ha"], risposte: ["ha", "hai", "ho", "hanno"] },
  { frase: "Marco ___ un regalo speciale", corretta: ["ha"], risposte: ["ha", "ho", "hanno", "hai"] },
  { frase: "Io e Luca ___ una missione importante", corretta: ["abbiamo"], risposte: ["abbiamo", "avete", "hanno", "ho"] },
  { frase: "Tu e Anna ___ un’occasione unica", corretta: ["avete"], risposte: ["avete", "abbiamo", "ha", "hanno"] },
  { frase: "Marco e Giulia ___ un invito per te", corretta: ["hanno"], risposte: ["hanno", "ha", "abbiamo", "avete"] },
      { frase: "Io ___ una casa", corretta: ["ho"], risposte: ["hai", "ho", "ha", "abbiamo"] },
      { frase: "Tu ___ un cane", corretta: ["hai"], risposte: ["ho", "hai", "ha", "avete"] },
      { frase: "Lui ___ una macchina", corretta: ["ha"], risposte: ["hai", "ho", "ha", "hanno"] },
      { frase: "Noi ___ due figli", corretta: ["abbiamo"], risposte: ["abbiamo", "avete", "hanno", "ho"] },
      { frase: "Voi ___ un problema", corretta: ["avete"], risposte: ["hai", "avete", "hanno", "ha"] },
      { frase: "Loro ___ fame", corretta: ["hanno"], risposte: ["ha", "hanno", "abbiamo", "hai"] },
      { frase: "Io ___ sonno", corretta: ["ho"], risposte: ["ho", "hai", "ha", "hanno"] },
      { frase: "Tu ___ ragione", corretta: ["hai"], risposte: ["ho", "hai", "ha", "hanno"] },
      { frase: "Lui ___ paura", corretta: ["ha"], risposte: ["ha", "ho", "hanno", "hai"] },
      { frase: "Lei ___ sete", corretta: ["ha"], risposte: ["ha", "hanno", "ho", "hai"] },
      { frase: "Noi ___ tempo", corretta: ["abbiamo"], risposte: ["abbiamo", "hanno", "avete", "ho"] },
      { frase: "Voi ___ fretta", corretta: ["avete"], risposte: ["avete", "abbiamo", "hanno", "ho"] },
      { frase: "Loro ___ bisogno", corretta: ["hanno"], risposte: ["hanno", "ha", "abbiamo", "avete"] },
      { frase: "Io ___ un’idea", corretta: ["ho"], risposte: ["ho", "hai", "hanno", "avete"] },
      { frase: "Tu ___ un sogno", corretta: ["hai"], risposte: ["hai", "ho", "ha", "hanno"] },
      { frase: "Lui ___ un dubbio", corretta: ["ha"], risposte: ["ha", "hanno", "ho", "hai"] },
      { frase: "Lei ___ un problema", corretta: ["ha"], risposte: ["ha", "ho", "hanno", "hai"] },
      { frase: "Noi ___ due macchine", corretta: ["abbiamo"], risposte: ["abbiamo", "avete", "hanno", "ho"] },
      { frase: "Voi ___ una soluzione", corretta: ["avete"], risposte: ["avete", "abbiamo", "hanno", "ha"] },
      { frase: "Loro ___ molto lavoro", corretta: ["hanno"], risposte: ["hanno", "ha", "abbiamo", "avete"] },
      { frase: "Io ___ un segreto", corretta: ["ho"], risposte: ["ho", "hai", "ha", "hanno"] },
      { frase: "Tu ___ un biglietto", corretta: ["hai"], risposte: ["hai", "ho", "hanno", "avete"] },
      { frase: "Lui ___ un regalo", corretta: ["ha"], risposte: ["ha", "ho", "hanno", "hai"] },
      { frase: "Noi ___ un progetto", corretta: ["abbiamo"], risposte: ["abbiamo", "avete", "hanno", "ho"] },
      { frase: "Voi ___ un’opportunità", corretta: ["avete"], risposte: ["avete", "abbiamo", "ha", "hanno"] },
      { frase: "Loro ___ un invito", corretta: ["hanno"], risposte: ["hanno", "ha", "abbiamo", "avete"] }
       ]
    },
    
    "Participio passato": {
        descrizione: " Es: (Verbo: comprare) Lei ha ___ un libro. => Lei ha COMPRATO un libro.",
       domande:[
     { frase: "(Verbo: rompere) Hai ___ il vaso?", corretta: ["rotto"], risposte: ["rotto", "romputo", "rompito", "rupto"] },
{ frase: "(Verbo: tradurre) Ho ___ il testo", corretta: ["tradotto"], risposte: ["tradotto", "tradito", "tratto", "traduciuto"] },
{ frase: "(Verbo: discutere) Abbiamo ___ molto", corretta: ["discusso"], risposte: ["discusso", "discututo", "discussato", "discotto"] },
{ frase: "(Verbo: piangere) Ha ___ per ore", corretta: ["pianto"], risposte: ["pianto", "pianguto", "piangito", "piangiuto"] },
{ frase: "(Verbo: spegnere) Hai ___ la luce?", corretta: ["spento"], risposte: ["spento", "spegnuto", "spenguto", "spinto"] },
{ frase: "(Verbo: accendere) Ho ___ la radio", corretta: ["acceso","accesa"], risposte: ["acceso", "accesa", "accessato", "accenduto"] },
{ frase: "(Verbo: ridere) Hanno ___ tanto", corretta: ["riso"], risposte: ["riso", "riduto", "ridato", "risuto"] },
{ frase: "(Verbo: succedere) È ___ un incidente", corretta: ["successo"], risposte: ["successo", "succeduto", "succedato", "succeso"] },
{ frase: "(Verbo: bere) Hai ___ troppo vino", corretta: ["bevuto"], risposte: ["bevuto", "bevito", "bevvuto", "beuto"] },
{ frase: "(Verbo: conoscere) Ho ___ una persona gentile", corretta: ["conosciuto","conosciuta"], risposte: ["conosciuto", "conosciato", "conosciuta", "conossuto"] },

{ frase: "(Verbo: coprire) Hai ___ il bambino?", corretta: ["coperto"], risposte: ["coperto", "coprito", "coprato", "copruto"] },
{ frase: "(Verbo: risolvere) Ho ___ il problema", corretta: ["risolto"], risposte: ["risolto", "risolvuto", "risolvito", "risoluto"] },
{ frase: "(Verbo: crescere) I bambini sono ___ molto", corretta: ["cresciuti"], risposte: ["cresciuti", "cresciuto", "cresciati", "cresciti"] },
{ frase: "(Verbo: deludere) L’esame mi ha ___", corretta: ["deluso"], risposte: ["deluso", "deluduto", "deludito", "delusato"] },
{ frase: "(Verbo: appendere) Ho ___ il quadro", corretta: ["appeso"], risposte: ["appeso", "appenduto", "appensato", "appesato"] },
{ frase: "(Verbo: cuocere) Hai ___ la pasta?", corretta: ["cotto"], risposte: ["cotto", "cotta", "cucito", "cuocato"] },
{ frase: "(Verbo: promettere) Mi hai ___ di venire", corretta: ["promesso"], risposte: ["promesso", "promettuto", "promitato", "promessato"] },
{ frase: "(Verbo: muovere) Ho ___ la sedia", corretta: ["mosso"], risposte: ["mosso", "mossa", "movuto", "muovuto"] },
{ frase: "(Verbo: ridurre) Abbiamo ___ i costi", corretta: ["ridotto"], risposte: ["ridotto", "ridurto", "ridotti", "riducito"] },
{ frase: "(Verbo: vincere) Hai ___ la partita?", corretta: ["vinto"], risposte: ["vinto", "vinciuto", "vinta", "vencuto"] },

    { frase: "(Verbo: rimanere) Io sono ___ a casa", corretta: ["rimasto"], risposte: ["rimanuto", "rimesso", "rimasto", "rimanto"] },
    { frase: "(Verbo: fare) Abbiamo ___ i compiti", corretta: ["fatto","fatti"], risposte: ["fatto", "fatti", "fatta", "fatuto"] },
    { frase: "(Verbo: vedere) Hai ___ il film?", corretta: ["visto"], risposte: ["veduto", "visto", "vedato", "vissuto"] },
    { frase: "(Verbo: dire) Marco ha ___ la verità", corretta: ["detto","detta"], risposte: ["detto", "dicto", "disto", "detta"] },
    { frase: "(Verbo: prendere) Ho ___ un caffè", corretta: ["preso"], risposte: ["prenduto", "preso", "presso", "presto"] },
    { frase: "(Verbo: venire) Siamo ___ a piedi", corretta: ["venuti"], risposte: ["vienuti", "venuti", "venato", "veniti"] },
    { frase: "(Verbo: aprire) Hai ___ la finestra?", corretta: ["aperto","aperta"], risposte: ["aperto", "aprito", "aperta", "apruto"] },
    { frase: "(Verbo: leggere) Ho ___ quel libro", corretta: ["letto"], risposte: ["lettato", "letto", "leggiuto", "leto"] },
    { frase: "(Verbo: scrivere) Lucia ha ___ una poesia", corretta: ["scritto"], risposte: ["scrivuto", "scrivito", "scritto", "scritta"] },
    { frase: "(Verbo: essere) Sono ___ a Roma", corretta: ["stato"], risposte: ["stato", "essuto", "estato", "essito"] },

    { frase: "(Verbo: correre) Ho ___ per prendere il treno", corretta: ["corso"], risposte: ["corso", "corruto", "corrito", "corsuto"] },
    { frase: "(Verbo: scegliere) Hai ___ il colore?", corretta: ["scelto"], risposte: ["scelto", "scegliuto", "sceltato", "scelguto"] },
    { frase: "(Verbo: perdere) Abbiamo ___ le chiavi", corretta: ["perso"], risposte: ["perduto", "perso", "perdito", "perdato"] },
    { frase: "(Verbo: chiudere) Hai ___ la porta?", corretta: ["chiuso"], risposte: ["chiuso", "chiudato", "chiudito", "chiusa"] },
    { frase: "(Verbo: nascere) Mio fratello è ___ a maggio", corretta: ["nato"], risposte: ["nato", "nascuto", "nasciuto", "nasciato"] },
    { frase: "(Verbo: mettere) Ho ___ il libro sul tavolo", corretta: ["messo"], risposte: ["messo", "mettuto", "mettato", "meso"] },
    { frase: "(Verbo: morire) Il gatto è ___ ieri", corretta: ["morto"], risposte: ["morto", "moruto", "morrato", "morrito"] },
    { frase: "(Verbo: rispondere) Hai ___ alla domanda?", corretta: ["risposto"], risposte: ["risposto", "risponduto", "rispoto", "risposo"] },
    { frase: "(Verbo: scendere) Sono ___ dall'autobus", corretta: ["sceso"], risposte: ["scenduto", "sceso", "scendato", "scesso"] },
    { frase: "(Verbo: vivere) Ha ___ in Italia per due anni", corretta: ["vissuto"], risposte: ["vissuto", "vivuto", "visto", "vivato"] },

    { frase: "(Verbo: parlare) Ieri ho ___ con Lucia", corretta: ["parlato"], risposte: ["parlato", "parlata", "parlatto", "parluto"] },
    { frase: "(Verbo: mangiare) Abbiamo ___ la pizza", corretta: ["mangiato","mangiata"], risposte: ["mangiato", "mangiata", "mangiatto", "mangato"] },
    { frase: "(Verbo: guardare) Hai ___ quel film?", corretta: ["guardato"], risposte: ["guardato", "guardita", "guarduto", "guardita"] },
    { frase: "(Verbo: ascoltare) Ho ___ la tua canzone", corretta: ["ascoltato","ascoltata"], risposte: ["ascoltato", "ascoltatto", "ascoltata", "ascoltuto"] },
    { frase: "(Verbo: lavorare) Maria ha ___ tutto il giorno", corretta: ["lavorato"], risposte: ["lavorato", "lavorata", "lavoruto", "lavoratto"] },
    { frase: "(Verbo: abitare) Ho ___ a Roma per due anni", corretta: ["abitato"], risposte: ["abitato", "abituta", "abitata", "abituato"] },
    { frase: "(Verbo: camminare) Abbiamo ___ per ore", corretta: ["camminato"], risposte: ["camminato", "caminato", "camminuta", "camminatto"] },
    { frase: "(Verbo: studiare) Hai ___ per l’esame?", corretta: ["studiato"], risposte: ["studiato", "studiatto", "studiuta", "studato"] },
    { frase: "(Verbo: comprare) Ho ___ il pane", corretta: ["comprato"], risposte: ["comprato", "compruta", "compreso", "compratto"] },
    { frase: "(Verbo: telefonare) Marco ha ___ a sua madre", corretta: ["telefonato"], risposte: ["telefonato", "telefonatto", "telefonuto", "telefonata"] }
  ]
},

    "Passato prossimo" : {
        descrizione: "Completa la frase",
       domande: [
  { frase: "(Verbo: telefonare) Ieri Marco ___ a sua madre", corretta: ["ha telefonato"], risposte: ["ha telefonato", "ho telefonato", "è telefonato", "ha telefonata"] },
  { frase: "(Verbo: vivere) Maria  ___ in Italia per due anni", corretta: ["ha vissuto", "è vissuta"], risposte: ["è vissuta", "ha vissuto", "è vissuto", "e vissuta"] },
  { frase: "(Verbo: scrivere) Ieri Luigi ___ una lunga lettera", corretta: ["ha scritto"], risposte: ["ha scritto", "è scritto", "ha scrivuto", "a scritto"] },
  { frase: "(Verbo: salire) Pochi minuti fa noi ___ sul treno", corretta: ["siamo saliti"], risposte: ["siamo saliti", "abbiamo saliti", "sono saliti", "siamo salito"] },
  { frase: "(Verbo: vedere) Ieri sera io ___ un bel film", corretta: ["ho visto"], risposte: ["ho visto", "ho veduto", "sono visto", "ha visto"] },
  { frase: "(Verbo: restare) Domanica passata Anna e Maria ___ a casa tutto il giorno", corretta: ["sono restate"], risposte: ["sono restati", "hanno restato", "sono restato", "sono restate"] },
  { frase: "(Verbo: accendere) Al tramonto Marco ___ la luce", corretta: ["ha acceso"], risposte: ["ha acceso", "ha accenduto", "è acceso", "ho acceso"] },
  { frase: "(Verbo: arrivare)  Carla, ieri tu  ___ in ritardo", corretta: ["sei arrivata"], risposte: ["sei arrivata", "ha arrivata", "sei arrivato", "è arrivate"] },
  { frase: "(Verbo: perdere) Ieri voi ___ le chiavi", corretta: ["avete perso","avete perduto"], risposte: ["avete perso", "siete persi", "avete perduto", "ha perso"] },
  { frase: "(Verbo: svegliarsi) Ero stanca e mi ___ tardi", corretta: ["sono svegliata"], risposte: ["sono svegliato", "mi sono svegliata", "mi ho svegliato", "mi è svegliato"] },
  { frase: "(Verbo: leggere) Tu ___ quel libro?", corretta: ["hai letto"], risposte: ["hai letto", "sei letto", "ai letto", "hai leggiuto"] },
  { frase: "(Verbo: uscire) Io Carlo e Maria ___ alle otto", corretta: ["siamo usciti"], risposte: ["siamo usciti", "abbiamo usciti", "sono usciti", "siamo uscite"] },
  { frase: "(Verbo: cadere) Ieri lei ___ dalle scale", corretta: ["è caduta"], risposte: ["è caduta", "ha caduto", "è caduto", "ha caduta"] },
  { frase: "(Verbo: dormire) La notte scorsa i bambini ___ bene", corretta: ["hanno dormito"], risposte: ["hanno dormito", "sono dormiti", "anno dormito", "ha dormito"] },
  { frase: "(Verbo: bere) Durante il pranzo noi ___ troppo vino", corretta: ["abbiamo bevuto"], risposte: ["abbiamo bevuto", "abbiamo beuto", "siamo bevuti", "abbiamo beviti"] },
  { frase: "(Verbo: partire) Perchè tu ___ presto?", corretta: ["sei partito"], risposte: ["sei partito", "hai partito", "sei partiti", "sei partita"] },
  { frase: "(Verbo: scendere) Io ___ per le scale lentamente", corretta: ["sono sceso"], risposte: ["sono sceso", "ho sceso", "è sceso", "ho scenduto"] },
  { frase: "(Verbo: comprare) Ieri Marco e Luisa  ___ una casa nuova", corretta: ["hanno comprato"], risposte: ["hanno comprato", "sono comprati", "hanno comprare", "anno comprato"] },
  { frase: "(Verbo: finire) Tu ___ i compiti?", corretta: ["hai finito","hai finiti"], risposte: ["hai finito", "sei finito", "hai finiti", "ai finito"] },
  { frase: "(Verbo: diventare) Lui ___ famoso", corretta: ["è diventato", "è divenuto"], risposte: ["è diventato", "ha diventato", "è divenuto", "e diventato"] },
         
  { frase: "(Verbo: spegnere) Ieri sera io ___ la TV", corretta: ["ho spento"], risposte: ["ho spento", "è spento", "o spento", "ha spento"] },
  { frase: "(Verbo: salire) Marta ___  per le scale di corsa", corretta: ["è salita"], risposte: ["è salita", "ha salito", "è salite", "ha salita"] },
  { frase: "(Verbo: rompere) I bambini ___ un bicchiere", corretta: ["hanno rotto"], risposte: ["hanno rotto", "sono rotti", "anno rotto", "ha rotto"] },
  { frase: "(Verbo: nascere) Tuo figlio ___ a giugno", corretta: ["è nato"], risposte: ["è nato", "ha nato", "è nascuto", "e nato"] },
  { frase: "(Verbo: entrare) L’amico di Marco ___ senza bussare", corretta: ["è entrato"], risposte: ["è entrato", "ha entrato", "è entrata", "sei  entrato"] },
  { frase: "(Verbo: spiegare) La professoressa ___ bene la lezione", corretta: ["ha spiegato"], risposte: ["ha spiegato", "è spiegata", "ha spiegata", "ha spieguto"] },
  { frase: "(Verbo: uscire) Carla e Lucia ___ tardi", corretta: ["sono uscite"], risposte: ["sono uscite", "hanno uscite", "sono uscita", "sono usciti"] },
  { frase: "(Verbo: cadere) Le foglie ___ dagli alberi", corretta: ["sono cadute"], risposte: ["sono cadute", "sono caduti", "hanno caduto", "sono cadate"] },
  { frase: "(Verbo: ridere) Noi ___ molto ieri", corretta: ["abbiamo riso"], risposte: ["abbiamo riso", "siamo risi", "abbiamo risi", "abbiamo risati"] },
  { frase: "(Verbo: tornare) Voi e Guido ___ tardi a casa", corretta: ["siete tornati"], risposte: ["siete tornati", "avete tornato", "sono tornati", "siete tornate"] },
  { frase: "(Verbo: crescere) Mio fratello ___ in fretta", corretta: ["è cresciuto"], risposte: ["è cresciuto", "ha cresciuto", "è crescito", "e cresciuto"] },
  { frase: "(Verbo: piangere) Il bambino ___ per ore", corretta: ["ha pianto"], risposte: ["ha pianto", "è pianto", "ha pianguto", "a pianto"] },
  { frase: "(Verbo: cambiare) Io ___ lavoro il mese scorso", corretta: ["ho cambiato"], risposte: ["ho cambiato", "sono cambiato", "ha cambiato", "o cambiato"] },
  { frase: "(Verbo: sembrare) A tutti ___ una buona idea", corretta: ["è sembrata"], risposte: ["è sembrata", "è  sembrato", "e sembrata", "ha sembrito"] },
  { frase: "(Verbo: finire) Loro ___ il progetto ieri", corretta: ["hanno finito"], risposte: ["hanno finito", "sono finiti", "hanno finati", "anno finito"] },
  { frase: "(Verbo: succedere) Cosa ___ ieri sera?", corretta: ["è successo"], risposte: ["è successo", "ha successo", "è succeduto", "e successo"] },
  { frase: "(Verbo: salire) I ragazzi ___ sul pullman", corretta: ["sono saliti"], risposte: ["sono saliti", "hanno salito", "sono salita", "sono salite"] },
  { frase: "(Verbo: visitare) Io e Anna ___ il museo", corretta: ["abbiamo visitato"], risposte: ["abbiamo visitato", "siamo visitati", "abbiamo visito", "habbiamo visitato"] },
  { frase: "(Verbo: servire) Il cameriere ___ il vino", corretta: ["ha servito"], risposte: ["ha servito", "è servito", "ha servuta", "a servito"] },
  { frase: "(Verbo: alzarsi) Stamattina io mi ___ presto", corretta: ["sono alzato"], risposte: ["sono alzato", "ho alzato", "mi ho alzato", "mi è alzato"] },


  // Frasi aggiunte
  { frase: "(Verbo: correre) Voi ___ al parco subito", corretta: ["siete corsi"], risposte: ["siete corsi", "avete corso", "sono corso", "siete corso"] },
  { frase: "(Verbo: piovere) Ieri ___ tutto il giorno", corretta: ["ha piovuto"], risposte: ["ha piovuto", "è piovuto", "piovette", "ha piovato"] }
    ]
},
    "Imperfetto indicativo": {
        descrizione: "Completa la frase",
       domande: [
  { frase: "(Verbo: parlare) Voi ___ a bassa voce quando è entrato il professore.", corretta: ["parlavate"], risposte: ["parlavate", "avete parlato", "parlaste", "parlavano"] },
  { frase: "(Verbo: parlare) Mentre voi ___ con lui, è arrivata una telefonata.", corretta: ["parlavate"], risposte: ["parlavate", "parlaste", "avete parlato", "parlate"] },
  { frase: "(Verbo: giocare) Voi ___ spesso nel cortile della scuola.", corretta: ["giocavate"], risposte: ["giocavate", "giocavi", "giocate", "avete giocato"] },
  { frase: "(Verbo: vedere) Da piccolo tu ___ molti cartoni animati.", corretta: ["vedevi"], risposte: ["vedevi", "vedeva", "vedeve", "hai visto"] },
  { frase: "(Verbo: ascoltare) Mentre ___ la musica,  ho sentito squillare il telefono.", corretta: ["ascoltavo"], risposte: ["ascoltavo", "ascoltai", "ho ascoltato", "ascolto"] },
  { frase: "(Verbo: leggere) Tu ___ il giornale quando ti ho chiamato?", corretta: ["leggevi"], risposte: ["hai letto", "leggeva", "leggevi", "lessi"] },
  { frase: "(Verbo: leggere) Mentre Marco___ il libro, ho sentito bussare alla porta.", corretta: ["leggeva"], risposte: ["leggeva", "lesse", "ha letto", "legge"] },
  { frase: "(Verbo: cucinare) Mentre mamma ___, il telefono ha squillato.", corretta: ["cucinava"], risposte: ["ha cucinato", "cucinava", "cucinò", "cucinavai"] },
  { frase: "(Verbo: scrivere) Mentre io  ___ una lettera, la penna ha smesso di funzionare.", corretta: ["scrivevo"], risposte: ["scrivevo", "scrissi", "ho scritto", "scrivo"] },
  { frase: "(Verbo: cucinare) Mentre noi ___ la cena, la luce è andata via.", corretta: ["cucinavamo"], risposte: ["cucinavamo", "abbiamo cucinato", "cucinammo", "cuciniamo"] },
  { frase: "(Verbo: dormire) Quando faceva freddo, noi ___ fino a tardi.", corretta: ["dormivamo"], risposte: ["dormivamo", "abbiamo dormito", "dormiamo", "dormivate"] },
  { frase: "(Verbo: scrivere) Da giovane lui ___ sempre lettere lunghissime.", corretta: ["scriveva"], risposte: ["scriveva", "scrivava", "ha scritto", "scrivevo"] },
  { frase: "(Verbo: camminare) Mentre ___ per strada, ho incontrato un vecchio amico.", corretta: ["camminavo"], risposte: ["camminavo", "cammino", "camminai", "ho camminato"] },
  { frase: "(Verbo: leggere) Quando ero piccolo io ___ le fiabe.", corretta: ["leggevo"], risposte: ["ho letto", "leggevo", "leggievo", "leggeva"] },
  { frase: "(Verbo: guardare) Ieri sera mentre noi  ___ un bel film, è arrivato mio fratello", corretta: ["guardavamo"], risposte: ["abbiamo guardato", "guardavamo", "guardammo", "siamo guardati"] },
  { frase: "(Verbo: mangiare) Mentre ___ la minestra , ho sentito un rumore strano.", corretta: ["mangiavo"], risposte: ["mangiavo", "ho mangiato", "mangiai", "mangio"] },
  { frase: "(Verbo: dormire) Mentre ___ profondamente, qualcuno ha bussato alla porta.", corretta: ["dormivo"], risposte: ["dormivo", "ho dormito", "dormii", "dormo"] },
  { frase: "(Verbo: scrivere) Ogni giorno, da bambina,  lei ___ una pagina del suo diario.", corretta: ["scriveva"], risposte: ["scriveva", "scrivava", "ha scritto", "scrivesse"] },
  { frase: "(Verbo: studiare) Mentre ___ per l’esame, mi è venuto mal di testa.", corretta: ["studiavo"], risposte: ["studiavo", "studio", "studiai", "ho studiato"] },
  { frase: "(Verbo: dormire) Quando è suonata la sveglia, voi ___ profondamente.", corretta: ["dormivate"], risposte: ["dormivate", "avete dormito", "dormivi", "dormivete"] },
  { frase: "(Verbo: andare) Da bambino tu ___ al mare ogni estate.", corretta: ["andavi"], risposte: ["sei andato", "andavi", "andave", "andava"] },
  { frase: "(Verbo: essere) Quando ero piccolo, la mia casa ___ vicino al fiume.", corretta: ["era"], risposte: ["era", "è", "erae", "fu"] },
  { frase: "(Verbo: correre) Io ___ nel parco ogni mattina prima della scuola.", corretta: ["correvo"], risposte: ["ho corso", "correvo", "corse", "corravo"] },
  { frase: "(Verbo: parlare) Quando è entrato il professore, ___ con i miei compagni.", corretta: ["parlavo"], risposte: ["parlavo", "parlai", "parlo", "ho parlato"] },
  { frase: "(Verbo: scrivere) Quando mi hai chiamato, ___ una mail importante.", corretta: ["scrivevo"], risposte: ["scrivevo", "ho scritto", "scrissi", "scrivo"] },
  { frase: "(Verbo: guardare) Mentre ___ la televisione, il gatto è saltato sul tavolo.", corretta: ["guardavo"], risposte: ["guardavo", "ho guardato", "guardai", "guardo"] },
  { frase: "(Verbo: bere) Da piccolo non ___ mai il latte.", corretta: ["bevevo"], risposte: ["bevevo", "bevvo", "ho bevuto", "beveva"] },
  { frase: "(Verbo: studiare) Quando eravamo al liceo, noi ___ molto per gli esami.", corretta: ["studiavamo"], risposte: ["studiammo", "studiavamo", "abbiamo studiato", "studievamo"] },
  { frase: "(Verbo: avere) Da bambino io ___ paura del buio.", corretta: ["avevo"], risposte: ["avevo", "ho avuto", "aveva", "avievo"] },
  { frase: "(Verbo: fare) I miei nonni ___ il pane in casa ogni sabato.", corretta: ["facevano"], risposte: ["facevano", "fanno", "faccevano", "hanno fatto"] },
  { frase: "(Verbo: suonare) Quando ero piccolo ___ il pianoforte ogni giorno.", corretta: ["suonavo"], risposte: ["suonavo", "ho suonato", "suonai", "suonavano"] },
{ frase: "(Verbo: vivere) Noi ___ in campagna quando ero bambino.", corretta: ["vivevamo"], risposte: ["vivevamo", "abbiamo vissuto", "vivavamo", "vivemmo"] },
{ frase: "(Verbo: pensare) Tu ___ spesso ai tuoi nonni?", corretta: ["pensavi"], risposte: ["pensavi", "hai pensato", "pensava", "pensasti"] },
{ frase: "(Verbo: volere) Da ragazzo ___ diventare medico.", corretta: ["volevo"], risposte: ["volevo", "voglio", "volle", "ho voluto"] },
{ frase: "(Verbo: sapere) Lei ___ già tutto quello che era successo.", corretta: ["sapeva"], risposte: ["sapeva", "ha saputo", "sappiava", "sapea"] },
{ frase: "(Verbo: potere) Quando ero giovane non ___ uscire da solo.", corretta: ["potevo"], risposte: ["potevo", "posso", "poteva", "ho potuto"] },
{ frase: "(Verbo: dovere) Da piccolo ___ sempre aiutare in casa.", corretta: ["dovevo"], risposte: ["dovevo", "ho dovuto", "doveva", "doverei"] },
{ frase: "(Verbo: viaggiare) Ogni estate noi ___ in Europa.", corretta: ["viaggiavamo"], risposte: ["viaggiavamo", "abbiamo viaggiato", "viaggiamo", "viaggiaste"] },
{ frase: "(Verbo: guardare) Tu ___ sempre i cartoni la domenica mattina.", corretta: ["guardavi"], risposte: ["guardavi", "guardasti", "hai guardato", "guardava"] },
{ frase: "(Verbo: abitare) Loro ___ in un piccolo paese di montagna.", corretta: ["abitavano"], risposte: ["abitavano", "abitarono", "hanno abitato", "abitavamo"] },
{ frase: "(Verbo: studiare) Io ___ ogni sera dopo cena.", corretta: ["studiavo"], risposte: ["studiavo", "ho studiato", "studio", "studiavi"] },
{ frase: "(Verbo: mettere) Mentre ___ in ordine i libri, è caduta una fotografia.", corretta: ["mettevo"], risposte: ["mettevo", "ho messo", "misi", "mettevi"] },
{ frase: "(Verbo: sentire) Tu ___ un rumore strano?", corretta: ["sentivi"], risposte: ["sentivi", "hai sentito", "sentisti", "senti"] },
{ frase: "(Verbo: capire) Mentre il professore spiegava, io non ___ nulla.", corretta: ["capivo"], risposte: ["capivo", "capii", "ho capito", "capiscevo"] },
{ frase: "(Verbo: fare) Voi ___ spesso passeggiate in montagna.", corretta: ["facevate"], risposte: ["facevate", "avete fatto", "faceste", "fate"] },
{ frase: "(Verbo: dire) Mia nonna sempre mi ___ di essere gentile.", corretta: ["diceva"], risposte: ["diceva", "disse", "ha detto", "dicette"] },
{ frase: "(Verbo: vedere) Ogni sera noi ___ le stelle dal terrazzo.", corretta: ["vedevamo"], risposte: ["vedevamo", "abbiamo visto", "vedevo", "vedevate"] },
{ frase: "(Verbo: ascoltare) Ogni mattina lei ___ la radio mentre faceva colazione.", corretta: ["ascoltava"], risposte: ["ascoltava", "ha ascoltato", "ascoltai", "ascolta"] },
{ frase: "(Verbo: camminare) Mentre ___ sulla spiaggia, ho trovato una conchiglia.", corretta: ["camminavo"], risposte: ["camminavo", "cammino", "ho camminato", "camminai"] },
{ frase: "(Verbo: mangiare) Ogni domenica noi ___ dalla nonna.", corretta: ["mangiavamo"], risposte: ["mangiavamo", "abbiamo mangiato", "mangiammo", "mangiavate"] },

  { frase: "(Verbo: piovere) Quando siamo usciti, non ___ più.", corretta: ["pioveva"], risposte: ["ha piovuto", "pioveva", "piovuto", "stava piovendo"] }
       ]
    },


       
       
    "Articoli Determinativi": {
        descrizione: "Completa la frase",
       domande: [
      { frase: "___ ragazzo", corretta: ["il"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ fiore", corretta: ["il"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ studio", corretta: ["lo"], risposte: ["lo", "il", "la", "l'"] },
      { frase: "___ amica", corretta: ["l'"], risposte: ["l'", "la", "il", "lo"] },
      { frase: "___ casa", corretta: ["la"], risposte: ["la", "l'", "lo", "il"] },
      { frase: "___ zaino", corretta: ["lo"], risposte: ["lo", "il", "la", "l'"] },
      { frase: "___ mela", corretta: ["la"], risposte: ["la", "l'", "gli", "lo"] },
      { frase: "___ orologio", corretta: ["l'"], risposte: ["l'", "il", "lo", "la"] },
      { frase: "___ amico", corretta: ["l'"], risposte: ["l'", "il", "lo", "la"] },
      { frase: "___ specchio", corretta: ["lo"], risposte: ["lo", "il", "la", "l'"] },
      { frase: "___ stella", corretta: ["la"], risposte: ["la", "l'", "lo", "il"] },
      { frase: "___ uomini", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
      { frase: "___ case", corretta: ["le"], risposte: ["le", "i", "gli", "la"] },
      { frase: "___ alberi", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
      { frase: "___ acqua", corretta: ["l'"], risposte: ["l'", "la", "il", "le"] },
      { frase: "___ donne", corretta: ["le"], risposte: ["le", "gli", "i", "la"] },
      { frase: "___ occhio", corretta: ["l'"], risposte: ["l'", "lo", "il", "gli"] },
      { frase: "___ zii", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
      { frase: "___ mano", corretta: ["la"], risposte: ["la", "le", "l'", "il"] },
      { frase: "___ ombrello", corretta: ["l'"], risposte: ["l'", "lo", "il", "la"] },
      { frase: "___ fiori", corretta: ["i"], risposte: ["i", "gli", "le", "lo"] },

      { frase: "___ studente", corretta: ["lo"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ amica", corretta: ["l'"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ mela", corretta: ["la"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ zio", corretta: ["lo"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ libro", corretta: ["il"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ scuola", corretta: ["la"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ orologio", corretta: ["l'"], risposte: ["il", "lo", "la", "l'"] },
      { frase: "___ uomini", corretta: ["gli"], risposte: ["i", "gli", "le", "lo"] },
      { frase: "___ penna", corretta: ["la"], risposte: ["la", "il", "l'", "lo"] },
{ frase: "___ gnomo", corretta: ["lo"], risposte: ["lo", "il", "la", "l'"] },
{ frase: "___ idea", corretta: ["l'"], risposte: ["l'", "la", "lo", "il"] },
{ frase: "___ bicicletta", corretta: ["la"], risposte: ["la", "l'", "il", "le"] },
{ frase: "___ zoccolo", corretta: ["lo"], risposte: ["lo", "il", "la", "l'"] },
{ frase: "___ treno", corretta: ["il"], risposte: ["il", "lo", "l'", "la"] },
{ frase: "___ scuola", corretta: ["la"], risposte: ["la", "l'", "il", "le"] },
{ frase: "___ occhi", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
{ frase: "___ ospedale", corretta: ["l'"], risposte: ["l'", "lo", "il", "la"] },
{ frase: "___ uccelli", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
{ frase: "___ bambina", corretta: ["la"], risposte: ["la", "l'", "il", "lo"] },
{ frase: "___ studenti", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
{ frase: "___ ragazzi", corretta: ["i"], risposte: ["i", "gli", "le", "lo"] },
{ frase: "___ animali", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
{ frase: "___ libro", corretta: ["il"], risposte: ["il", "lo", "l'", "la"] },
{ frase: "___ inverno", corretta: ["l'"], risposte: ["l'", "lo", "il", "la"] },
{ frase: "___ elefante", corretta: ["l'"], risposte: ["l'", "lo", "il", "la"] },
{ frase: "___ gnocchi", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
{ frase: "___ tigre", corretta: ["la"], risposte: ["la", "l'", "lo", "il"] },
{ frase: "___ amici", corretta: ["gli"], risposte: ["gli", "i", "le", "lo"] },
      { frase: "___ case", corretta: ["le"], risposte: ["i", "gli", "le", "la"] }
    ]
},
    "Articoli Indeterminativi":  {
        descrizione: "Completa la frase",
       domande:[
      { frase: "___ isola", corretta: ["un'"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ arancia", corretta: ["un'"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ studente", corretta: ["uno"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ zaino", corretta: ["uno"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ mela", corretta: ["una"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ orologio", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ amico", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ amici", corretta: ["degli"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ penne", corretta: ["delle"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ isole", corretta: ["delle"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ uomini", corretta: ["degli"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ olio", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ amica", corretta: ["un'"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ zio", corretta: ["uno"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ libro", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ studentesse", corretta: ["delle"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ alberi", corretta: ["dei"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ casa", corretta: ["una"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ orchidee", corretta: ["delle"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ amori", corretta: ["degli"], risposte: ["dei", "degli", "delle", "dei'"] },
      { frase: "___ animale", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },

      { frase: "___ studente", corretta: ["uno"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ zaino", corretta: ["uno"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ mela", corretta: ["una"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ orologio", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ specchio", corretta: ["uno"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ finestra", corretta: ["una"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ amica", corretta: ["un'"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ stella", corretta: ["una"], risposte: ["un", "uno", "una", "un'"] },
      { frase: "___ ragazzo entra nella classe.", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ mela è sul tavolo.", corretta: ["una"], risposte: ["una", "un", "uno", "un'"] },
{ frase: "___ studente alza la mano.", corretta: ["uno"], risposte: ["uno", "un", "una", "un'"] },
{ frase: "___ amica mi chiama ogni giorno.", corretta: ["un'"], risposte: ["un'", "una", "un", "uno"] },
{ frase: "___ libro interessante!", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ zaino è caduto per terra.", corretta: ["uno"], risposte: ["uno", "un", "una", "un'"] },
{ frase: "___ casa grande è in vendita.", corretta: ["una"], risposte: ["una", "un", "un'", "uno"] },
{ frase: "___ uomo misterioso è entrato.", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ banana è troppo matura.", corretta: ["una"], risposte: ["una", "un", "uno", "un'"] },
{ frase: "___ psicologo è disponibile domani.", corretta: ["uno"], risposte: ["uno", "un", "una", "un'"] },
{ frase: "___ ape vola nel giardino.", corretta: ["un'"], risposte: ["un'", "una", "uno", "un"] },
{ frase: "___ telefono nuovo è sul tavolo.", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ scimmia salta sull’albero.", corretta: ["una"], risposte: ["una", "un", "uno", "un'"] },
{ frase: "___ studente straniero frequenta il corso.", corretta: ["uno"], risposte: ["uno", "un", "una", "un'"] },
{ frase: "___ artista espone le sue opere.", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ idea geniale!", corretta: ["un'"], risposte: ["un'", "una", "uno", "un"] },
{ frase: "___ orologio antico è in mostra.", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ ragazza entra in aula.", corretta: ["una"], risposte: ["una", "un", "un'", "uno"] },
{ frase: "___ zoo molto bello!", corretta: ["uno"], risposte: ["uno", "un", "una", "un'"] },
{ frase: "___ occasione da non perdere!", corretta: ["un'"], risposte: ["un'", "una", "un", "uno"] },
{ frase: "___ bambino gioca nel parco.", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] },
{ frase: "___ ragazzi giocano in cortile.", corretta: ["dei"], risposte: ["dei", "degli", "delle", "dei"] },
{ frase: "___ studenti parlano con l'insegnante.", corretta: ["degli"], risposte: ["dei", "degli", "delle", "dei"] },
{ frase: "___ bambine cantano una canzone.", corretta: ["delle"], risposte: ["delle", "dei", "degli", "le"] },
{ frase: "___ zaini sono per terra.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "gli"] },
{ frase: "___ amiche mi scrivono ogni giorno.", corretta: ["delle"], risposte: ["delle", "dei", "degli", "le"] },
{ frase: "___ alberi sono molto alti.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "gli"] },
{ frase: "___ ragazzi italiani partecipano al progetto.", corretta: ["dei"], risposte: ["dei", "degli", "delle", "i"] },
{ frase: "___ donne parlano tra loro.", corretta: ["delle"], risposte: ["delle", "degli", "dei", "le"] },
{ frase: "___ psicologi lavorano nella scuola.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "gli"] },
{ frase: "___ studenti stranieri arrivano oggi.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "gli"] },
{ frase: "___ amiche simpatiche mi hanno invitato.", corretta: ["delle"], risposte: ["delle", "dei", "degli", "le"] },
{ frase: "___ uomini parlano forte.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "gli"] },
{ frase: "___ libri sono sul tavolo.", corretta: ["dei"], risposte: ["dei", "degli", "delle", "i"] },
{ frase: "___ case hanno il tetto rosso.", corretta: ["delle"], risposte: ["delle", "dei", "degli", "le"] },
{ frase: "___ sportivi corrono al parco.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "i"] },
{ frase: "___ finestre sono aperte.", corretta: ["delle"], risposte: ["delle", "dei", "degli", "le"] },
{ frase: "___ studenti attenti ascoltano.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "i"] },
{ frase: "___ giornalisti scrivono l'articolo.", corretta: ["dei"], risposte: ["dei", "degli", "delle", "i"] },
{ frase: "___ insegnanti spiegano la lezione.", corretta: ["degli"], risposte: ["degli", "dei", "delle", "gli"] },
{ frase: "___ ragazze ridono forte.", corretta: ["delle"], risposte: ["delle", "degli", "dei", "le"] },

      { frase: "___ fiume", corretta: ["un"], risposte: ["un", "uno", "una", "un'"] }
    ]
},
    Preposizioni: {
        descrizione: "Completa la frase",
       domande: [
      { frase: "Mangio ___ ristorante", corretta: ["al","nel"], risposte: ["al", "alla", "nel", "sul", "in"] },
      { frase: "Andiamo ___ montagna", corretta: ["in"], risposte: ["in", "alla", "a", "su", "per"] },
      { frase: "Sono arrivato ___ aeroporto", corretta: ["all'","in"], risposte: ["all'", "al", "in", "da", "su"] },
      { frase: "Cammino ___ parco", corretta: ["nel"], risposte: ["nel", "al", "sul", "in", "da"] },
      { frase: "Aspetto ___ stazione", corretta: ["alla","nella","in"], risposte: ["alla", "al", "in", "da", "nella"] },
      { frase: "Vado ___ medico", corretta: ["dal"], risposte: ["dal", "al", "in", "per", "su"] },
      { frase: "Lucia lavora ___ banca", corretta: ["in"], risposte: ["in", "a", "da", "su", "per"] },
      { frase: "Parto ___  treno", corretta: ["in"], risposte: ["con", "su", "in", "per", "da"] },
      { frase: "Sono seduto ___ tavolo", corretta: ["al"], risposte: ["al", "sul", "nel", "in", "da"] },
      { frase: "Metto il vaso ___ tavolino", corretta: ["sul"], risposte: ["sul", "in", "al", "da", "nella"] },
      { frase: "Vado ___ cinema", corretta: ["al"], risposte: ["allo", "al", "in", "su", "da"] },
      { frase: "Leggo ___ letto", corretta: ["a"], risposte: ["a", "nel", "su", "dal", "per"] },
      { frase: "Bevo acqua ___ bicchiere", corretta: ["dal","nel"], risposte: ["dal", "al", "nel", "su", "per"] },
      { frase: "Giro ___ il centro della città", corretta: ["per"], risposte: ["per", "in", "a", "su", "tra"] },
      { frase: "Telefono ___ mia madre", corretta: ["a"], risposte: ["a", "in", "da", "per", "con"] },
      { frase: "Scrivo ___ computer", corretta: ["al","sul"], risposte: ["al", "sul", "nel", "in", "da"] },
      { frase: "Ci incontriamo ___ bar", corretta: ["al","nel"], risposte: ["al", "nel", "alla", "in", "da"] },
      { frase: "Vai ___ cinema", corretta: ["al"], risposte: ["al", "in", "alla", "su", "da"] },
      { frase: "Compro ___ mercato", corretta: ["al","nel"], risposte: ["al", "in", "nel", "sul", "per"] },
      { frase: "Ho comprato un regalo ___ negozio", corretta: ["nel"], risposte: ["nel", "al", "in", "da", "per"] },

      { frase: "Vado ___ Roma", corretta: ["a"], risposte: ["a", "in", "da", "su"] },
      { frase: "Abito ___ Italia", corretta: ["in"], risposte: ["a", "in", "da", "su"] },
      { frase: "Vengo ___ Francia", corretta: ["dalla","in"], risposte: ["a", "in", "dalla", "di"] },
      { frase: "Metto il libro ___ tavolo", corretta: ["sul"], risposte: ["a", "in", "da", "sul"] },
      { frase: "La penna è ___ borsa", corretta: ["nella","in"], risposte: ["nella", "sulla", "alla", "in"] },
      { frase: "Esco ___ casa", corretta: ["di","da"], risposte: ["di", "da", "in", "con"] },
      { frase: "Studio ___ biblioteca", corretta: ["in","nella"], risposte: ["in", "nella", "da", "su"] },
      { frase: "Il gatto è ___ sedia", corretta: ["sulla"], risposte: ["sulla", "nella", "alla", "dalla"] },
      { frase: "Parto ___ Milano", corretta: ["per","da"], risposte: ["per", "da", "in", "a"] },
      { frase: "Corro ___ strada", corretta: ["per","sulla"], risposte: ["per", "sulla", "alla", "in", "su"] },
{ frase: "Resto ___ casa stasera", corretta: ["a","in"], risposte: ["a", "in", "da", "per", "su"] },
{ frase: "Il quadro è appeso ___ parete", corretta: ["alla","sulla"], risposte: ["alla", "sulla", "in", "su", "da"] },
{ frase: "Ceniamo ___ ristorante giapponese", corretta: ["al"], risposte: ["al", "in", "dal", "sul", "alla"] },
{ frase: "Il treno parte ___ binario 3", corretta: ["dal"], risposte: ["dal", "sul", "nel", "alla", "da"] },
{ frase: "Passeggiamo ___ il centro storico", corretta: ["per"], risposte: ["per", "in", "a", "da", "tra"] },
{ frase: "Il libro è ___ scaffale", corretta: ["sullo","nello"], risposte: ["sullo", "nello", "al", "in", "su"] },
{ frase: "Ci vediamo ___ stazione", corretta: ["alla","in"], risposte: ["alla", "in", "al", "sulla", "da"] },
{ frase: "Mi siedo ___ sedia", corretta: ["sulla"], risposte: ["sulla", "nella", "alla", "in", "su"] },
{ frase: "I bambini giocano ___ giardino", corretta: ["in","nel"], risposte: ["in", "nel", "al", "da", "su"] },
{ frase: "Viaggiamo ___ auto", corretta: ["in"], risposte: ["in", "con", "su", "a", "da"] },
{ frase: "C'è una farmacia ___ angolo", corretta: ["all'","sull'"], risposte: ["all'", "sull'", "nel", "in", "da"] },
{ frase: "Torniamo ___ una vacanza", corretta: ["da"], risposte: ["da", "di", "in", "a", "per"] },
{ frase: "Andiamo ___ concerto stasera", corretta: ["al"], risposte: ["al", "in", "da", "su", "alla"] },
{ frase: "Il cane dorme ___ divano", corretta: ["sul","nel"], risposte: ["sul", "nel", "al", "da", "su"] },
{ frase: "Lavoro ___ centro della città", corretta: ["nel"], risposte: ["in", "nel", "al", "da", "per"] },
{ frase: "Sono arrivato ___ casa tardi", corretta: ["a","in"], risposte: ["a", "in", "da", "per", "su"] },
{ frase: "Lui viene ___ università", corretta: ["dall'", "all'"], risposte: ["dall'", "da", "in", "a", "su"] },
{ frase: "Stanno ___ spiaggia", corretta: ["in","sulla"], risposte: ["in", "sulla", "alla", "su", "da"] },
{ frase: "Ho lasciato il telefono ___ borsa", corretta: ["nella","in"], risposte: ["nella", "in", "alla", "sulla", "su"] },

      { frase: "Arrivo ___ stazione", corretta: ["alla","in","dalla","nella"], risposte: ["alla", "nella", "sulla", "dalla","in"] }
    ]
},
    "Aggettivi possessivi":  {
        descrizione: "Completa la frase",
       domande:[
  { frase: "Io e Mario abbiamo dimenticato la (<u><i>di noi</i></u>) borsa.", corretta: ["nostra"], risposte: ["nostra", "mia", "vostra", "loro"] },
  { frase: "Anna cerca il (<u><i>di lei</i></u>) telefono.", corretta: ["suo"], risposte: ["suo", "loro", "tuo", "nostro"] },
  { frase: "Tu hai chiuso le (<u><i>di te</i></u>) finestre?", corretta: ["tue"], risposte: ["sue", "tue", "mie", "loro"] },
  { frase: "Carlo e Luigi ascoltano i (<u><i>di loro</i></u>) dischi preferiti.", corretta: ["loro"], risposte: ["loro", "nostri", "vostri", "suoi"] },
  { frase: "Abbiamo incontrato la (<u><i>di voi</i></u>) insegnante ieri.", corretta: ["vostra"], risposte: ["nostra", "vostra", "loro", "tua"] },
  { frase: "Luca mostra le (<u><i>di lui</i></u>) chiavi.", corretta: ["sue"], risposte: ["sua", "loro", "sue", "tuo"] },
  { frase: "Io ho perso il (<u><i>di me</i></u>) portafoglio.", corretta: ["mio"], risposte: ["mio", "suo", "nostro", "loro"] },
  { frase: "Tu e Anna amate le (<u><i>di voi</i></u>) tradizioni.", corretta: ["vostre"], risposte: ["loro", "nostre", "vostre", "mie"] },
  { frase: "Loro leggono i (<u><i>di loro</i></u>) libri preferiti.", corretta: ["loro"], risposte: ["loro", "suoi", "vostri", "nostri"] },
  { frase: "Noi prepariamo la (<u><i>di noi</i></u>) cena ogni sera.", corretta: ["nostra"], risposte: ["vostra", "nostra", "loro", "mia"] },
  { frase: "Anna scrive nel (<u><i>di lei</i></u>) diario ogni giorno.", corretta: ["suo"], risposte: ["suo", "mio", "loro", "tuo"] },
  { frase: "Mario aspetta il (<u><i>di lui</i></u>) turno.", corretta: ["suo"], risposte: ["loro", "suo", "mio", "tuo"] },
  { frase: "Io ho ritrovato le (<u><i>di me</i></u>) scarpe.", corretta: ["mie"], risposte: ["mie", "sue", "loro", "miei"] },
  { frase: "Tu conservi bene le (<u><i>di te</i></u>) cose.", corretta: ["tue"], risposte: ["tue", "mie", "sue", "loro"] },
  { frase: "Carlo e Luigi hanno portato i (<u><i>di loro</i></u>) strumenti.", corretta: ["loro"], risposte: ["nostri", "loro", "vostri", "suoi"] },
  { frase: "Abbiamo visitato la (<u><i>di noi</i></u>) vecchia scuola.", corretta: ["nostra"], risposte: ["nostra", "vostra", "loro", "mia"] },
  { frase: "Avete ricevuto il (<u><i>di voi</i></u>) pacco?", corretta: ["vostro"], risposte: ["vostro", "nostro", "loro", "suo"] },
  { frase: "Anna ha venduto la (<u><i>di lei</i></u>) macchina.", corretta: ["sua"], risposte: ["sua", "mia", "nostra", "vostra"] },
  { frase: "Io e Anna parliamo delle (<u><i>di noi</i></u>) vacanze.", corretta: ["nostre"], risposte: ["vostre", "loro", "nostre", "mie"] },
  { frase: "Luca e tu aspettate i (<u><i>di voi</i></u>) amici.", corretta: ["vostri"], risposte: ["vostri", "loro", "nostri", "suoi"] },
  { frase: "Anna e Carlo hanno dimenticato le (<u><i>di loro</i></u>) valigie.", corretta: ["loro"], risposte: ["loro", "nostre", "vostre", "sue"] },
  { frase: "Io ho ascoltato il (<u><i>di me</i></u>) cuore.", corretta: ["mio"], risposte: ["mio", "tuo", "suo", "loro"] },
  { frase: "Tu e Mario avete acceso le (<u><i>di voi</i></u>) luci.", corretta: ["vostre"], risposte: ["nostre", "vostre", "loro", "sue"] },
  { frase: "Noi abbiamo perso le (<u><i>di noi</i></u>) chiavi.", corretta: ["nostre"], risposte: ["nostre", "vostre", "loro", "mie"] },
  { frase: "Luca prepara il (<u><i>di lui</i></u>) zaino.", corretta: ["suo"], risposte: ["suo", "loro", "mio", "nostro"] },
  { frase: "Anna ha acceso le (<u><i>di lei</i></u>) candele.", corretta: ["sue"], risposte: ["sue", "mie", "loro", "sui"] },
  { frase: "Io e tu ricordiamo le (<u><i>di noi</i></u>) promesse.", corretta: ["nostre"], risposte: ["nostre", "loro", "vostre", "mie"] },
  { frase: "Tu hai letto il (<u><i>di te</i></u>) libro?", corretta: ["tuo"], risposte: ["suo", "tuo", "vostro", "nostro"] },
  { frase: "Carlo ha lavato la (<u><i>di lui</i></u>) macchina.", corretta: ["sua"], risposte: ["sua", "mia", "vostra", "loro"] },
  { frase: "Maria ha rotto il (<u><i>di lei</i></u>) telefono.", corretta: ["suo"], risposte: ["suo", "mio", "vostro", "loro"] },
{ frase: "Avete dimenticato le (<u><i>di voi</i></u>) valigie?", corretta: ["vostre"], risposte: ["vostre", "loro", "nostre", "sue"] },
{ frase: "Io ho controllato la (<u><i>di me</i></u>) posta.", corretta: ["mia"], risposte: ["mia", "sua", "loro", "nostra"] },
{ frase: "Tu e Luca non trovate i (<u><i>di voi</i></u>) biglietti.", corretta: ["vostri"], risposte: ["vostri", "loro", "nostri", "suoi"] },
{ frase: "Abbiamo aperto la (<u><i>di noi</i></u>) finestra.", corretta: ["nostra"], risposte: ["nostra", "vostra", "mia", "sua"] },
{ frase: "Tu indossi le (<u><i>di te</i></u>) scarpe nuove.", corretta: ["tue"], risposte: ["tue", "mie", "sue", "tui"] },
{ frase: "Giovanni ha finito il (<u><i>di lui</i></u>) compito.", corretta: ["suo"], risposte: ["suo", "mio", "loro", "nostro"] },
{ frase: "Tu e Anna portate le (<u><i>di voi</i></u>) borse?", corretta: ["vostre"], risposte: ["vostre", "loro", "nostre", "sue"] },
{ frase: "Io e Luigi presentiamo i (<u><i>di noi</i></u>) amici.", corretta: ["nostri"], risposte: ["nostri", "vostri", "loro", "suoi"] },
{ frase: "Maria cerca le (<u><i>di lei</i></u>) chiavi.", corretta: ["sue"], risposte: ["sue", "mie", "tue", "sui"] },
{ frase: "Avete salutato il (<u><i>di voi</i></u>) professore?", corretta: ["vostro"], risposte: ["vostro", "nostro", "suo", "loro"] },
{ frase: "Luca e io sistemiamo la (<u><i>di noi</i></u>) camera.", corretta: ["nostra"], risposte: ["nostra", "loro", "mia", "vostra"] },
{ frase: "Tu guardi le (<u><i>di te</i></u>) serie preferite.", corretta: ["tue"], risposte: ["tue", "mie", "sue", "tui"] },
{ frase: "Loro hanno ordinato il (<u><i>di loro</i></u>) pranzo.", corretta: ["loro"], risposte: ["loro", "nostro", "suo", "vostro"] },
{ frase: "Noi beviamo il (<u><i>di noi</i></u>) tè.", corretta: ["nostro"], risposte: ["nostro", "vostro", "mio", "loro"] },
{ frase: "Tu hai dimenticato le (<u><i>di te</i></u>) chiavi?", corretta: ["tue"], risposte: ["tue", "mie", "sue", "tui"] },
{ frase: "Io leggo il (<u><i>di me</i></u>) giornale ogni mattina.", corretta: ["mio"], risposte: ["mio", "suo", "nostro", "vostro"] },
{ frase: "Anna e Paolo mangiano le (<u><i>di loro</i></u>) mele.", corretta: ["loro"], risposte: ["loro", "nostre", "vostre", "sue"] },
{ frase: "Giulia disegna con le (<u><i>di lei</i></u>) matite.", corretta: ["sue"], risposte: ["sue", "mie", "loro", "vostre"] },
{ frase: "Hai visto i (<u><i>di me</i></u>) libri?", corretta: ["miei"], risposte: ["miei", "tuoi", "suoi", "nostri"] },
{ frase: "Porti i (<u><i>di te</i></u>) documenti?", corretta: ["tuoi"], risposte: ["tuoi", "miei", "suoi", "vostri"] },
{ frase: "Marco ha dimenticato i (<u><i>di lui</i></u>) occhiali.", corretta: ["suoi"], risposte: ["suoi", "tuoi", "miei", "nostri"] },
{ frase: "Non trovo i (<u><i>di me</i></u>) appunti.", corretta: ["miei"], risposte: ["miei", "suoi", "tuoi", "vostri"] },
{ frase: "Hai sistemato i (<u><i>di te</i></u>) vestiti?", corretta: ["tuoi"], risposte: ["tuoi", "suoi", "miei", "nostri"] },
{ frase: "Giulia ha venduto i (<u><i>di lei</i></u>) libri.", corretta: ["suoi"], risposte: ["suoi", "tuoi", "miei", "nostri"] },
{ frase: "Questi sono i (<u><i>di me</i></u>) amici più cari.", corretta: ["miei"], risposte: ["miei", "mii", "suoi", "nostri"] },
{ frase: "Hai ricevuto i (<u><i>di te</i></u>) messaggi?", corretta: ["tuoi"], risposte: ["tuoi", "miei", "tui", "loro"] },
{ frase: "Luca ha trovato i (<u><i>di lui</i></u>) guanti.", corretta: ["suoi"], risposte: ["suoi", "tuoi", "suii", "nostri"] },
{ frase: "I (<u><i>di me</i></u>) sogni sono strani.", corretta: ["miei"], risposte: ["miei", "suoi", "tuoi", "loro"] },
{ frase: "Dove hai messo i (<u><i>di te</i></u>) occhiali?", corretta: ["tuoi"], risposte: ["tuoi", "tui", "suoi", "loro"] },
{ frase: "Marco non trova i (<u><i>di lui</i></u>) quaderni.", corretta: ["suoi"], risposte: ["suoi", "tuoi", "miei", "sui"] },

{ frase: "Io e te raccontiamo le (<u><i>di noi</i></u>) storie.", corretta: ["nostre"], risposte: ["nostre", "vostre", "loro", "mie"] },

  { frase: "Tu e Anna avete controllato i (<u><i>di voi</i></u>) documenti?", corretta: ["vostri"], risposte: ["vostri", "loro", "nostri", "suoi"] }
]
    },
Plurali :  {
        descrizione: "Es: Il libro pesante => I libri pesanti",
       domande:[
  { frase: "La vecchia madre", corretta: ["Le vecchie madri"], risposte: ["Le vecchie madre", "Le vecchie madri", "I vecchi madri", "Le vecchi madre"] },
  { frase: "Il ragazzo simpatico", corretta: ["I ragazzi simpatici"], risposte: ["I ragazzi simpatici", "Gli ragazzi simpatici", "I ragazze simpatiche", "I ragazzi simpatichi"] },
  { frase: "L’amico fedele", corretta: ["Gli amici fedeli"], risposte: ["Gli amici fedeli", "I amici fedeli", "Gli amichi fedeli", "Gli amici fedele"] },
  { frase: "La mela rossa", corretta: ["Le mele rosse"], risposte: ["Le mele rossi", "Le mele rosse", "I mele rosse", "Le meli rosse"] },
  { frase: "Il fiore profumato", corretta: ["I fiori profumati"], risposte: ["I fiori profumati", "I fiori profumate", "Gli fiori profumati", "Li fiori profumati"] },
  { frase: "L’automobile veloce", corretta: ["Le automobili veloci"], risposte: ["Le automobili veloce", "Le automobili veloci", "Gli automobili veloci", "Le automobile veloci"] },
  { frase: "Lo studente attento", corretta: ["Gli studenti attenti"], risposte: ["Gli studenti attenti", "I studenti attenti", "Gli studente attenti", "Li studenti attenti"] },
  { frase: "La casa grande", corretta: ["Le case grandi"], risposte: ["Le case grandi", "Le case grande", "I casi grandi", "Le casa grandi"] },
  { frase: "Il cane fedele", corretta: ["I cani fedeli"], risposte: ["I cani fedeli", "Gli cani fedeli", "I cane fedeli", "I cani fedele"] },
  { frase: "La bambina gentile", corretta: ["Le bambine gentili"], risposte: ["Le bambine gentili", "Le bambine gentile", "Le bambini gentili", "I bambini gentili"] },
  { frase: "Il gatto pigro", corretta: ["I gatti pigri"], risposte: ["I gatti pigri", "I gatto pigri", "Gli gatti pigri", "Li gatti pigri"] },
  { frase: "La finestra chiusa", corretta: ["Le finestre chiuse"], risposte: ["Le finestre chiuse", "Le finestre chiusi", "Le finestri chiuse", "I finestre chiuse"] },
  { frase: "Il libro interessante", corretta: ["I libri interessanti"], risposte: ["I libri interessanti", "I libri interessante", "Gli libri interessanti", "Li libri interessanti"] },
  { frase: "La scarpa nuova", corretta: ["Le scarpe nuove"], risposte: ["Le scarpe nuove", "Le scarpe nuovi", "Le scarpi nuove", "I scarpe nuovi"] },
  { frase: "Lo zaino pesante", corretta: ["Gli zaini pesanti"], risposte: ["Gli zaini pesanti", "I zaini pesanti", "I zaini pesante", "Gli zaini pesante"] },
  { frase: "Il vestito elegante", corretta: ["I vestiti eleganti"], risposte: ["I vestiti eleganti", "Gli vestiti elegante", "Gli vestiti eleganti", "I vestiti elegante"] },
  { frase: "La lezione noiosa", corretta: ["Le lezioni noiose"], risposte: ["Le lezioni noiose", "Le lezione noiose", "I lezioni noiose", "Le lezioni noiosi"] },
  { frase: "L’albero alto", corretta: ["Gli alberi alti"], risposte: ["Gli alberi alti", "I alberi alti", "Gli alberi alte", "Gli albere alti"] },
  { frase: "La porta aperta", corretta: ["Le porte aperte"], risposte: ["Le porte aperte", "Le porti aperte", "I porti aperti", "Le porte aperti"] },
  { frase: "Il bambino felice", corretta: ["I bambini felici"], risposte: ["I bambini felici", "I bambini felice", "Gli bambini felici", "I bambini felichi"] },
  { frase: "La notte tranquilla", corretta: ["Le notti tranquille"], risposte: ["Le notti tranquille", "Le notte tranquille", "Le notti tranquilli", "I notti tranquille"] },
  { frase: "Il giorno soleggiato", corretta: ["I giorni soleggiati"], risposte: ["I giorni soleggiati", "Le giorni soleggiati", "Gli giorni soleggiati", "Le giorni soleggiate"] },
  { frase: "La strada lunga", corretta: ["Le strade lunghe"], risposte: ["Le strade lunghe", "Le stradi lunghe", "Le strade lunge", "Le strade lunghi"] },
  { frase: "Il tavolo rotondo", corretta: ["I tavoli rotondi"], risposte: ["I tavoli rotondi", "I tavolo rotondi", "Gli tavoli rotondi", "Le tavoli rotonde"] },
  { frase: "La domanda difficile", corretta: ["Le domande difficili"], risposte: ["Le domande difficili", "Le domandi difficili", "Le domande difficile", "Le domande difficile"] },
  { frase: "Il problema complesso", corretta: ["I problemi complessi"], risposte: ["I problemi complessi", "I problema complessi", "Gli problemi complessi", "Le probleme complesse"] },
  { frase: "La parola gentile", corretta: ["Le parole gentili"], risposte: ["Le parole gentili", "Le paroli gentili", "Le parole gentile", "Le paroli gentile"] },
  { frase: "Il soldato coraggioso", corretta: ["I soldati coraggiosi"], risposte: ["I soldati coraggiosi", "I soldate coraggiosi", "Gli soldati coraggiosi", "I soldati coraggiose"] },
  { frase: "La canzone bella", corretta: ["Le canzoni belle"], risposte: ["Le canzoni belle", "Le canzone belle", "Le canzoni belli", "Le canzone belli"] },
  { frase: "La donna elegante", corretta: ["Le donne eleganti"], risposte: ["Le donne eleganti", "Le donna eleganti", "Le donne elegante", "I donne eleganti"] },
{ frase: "L’uomo forte", corretta: ["Gli uomini forti"], risposte: ["Gli uomini forti", "I uomini forti", "Gli uomo forti", "Gli uomini forte"] },
{ frase: "La voce chiara", corretta: ["Le voci chiare"], risposte: ["Le voci chiare", "Le voce chiare", "Le voci chiari", "I voci chiare"] },
{ frase: "Il piatto sporco", corretta: ["I piatti sporchi"], risposte: ["I piatti sporchi", "Gli piatti sporchi", "I piatti sporche", "I piatti sporci"] },
{ frase: "La sedia comoda", corretta: ["Le sedie comode"], risposte: ["Le sedie comode", "Le sedie comodi", "Le sedia comode", "I sedie comodi"] },
{ frase: "L’occhio attento", corretta: ["Gli occhi attenti"], risposte: ["Gli occhi attenti", "I occhi attenti", "Gli occhio attenti", "Gli occhi attente"] },
{ frase: "Il dente sano", corretta: ["I denti sani"], risposte: ["I denti sani", "Gli denti sani", "I dente sani", "I denti sane"] },
{ frase: "La parete bianca", corretta: ["Le pareti bianche"], risposte: ["Le pareti bianche", "Le pareti bianchi", "Le parete bianche", "I pareti bianchi"] },
{ frase: "Il vestito sporco", corretta: ["I vestiti sporchi"], risposte: ["I vestiti sporchi", "I vestiti sporche", "Gli vestiti sporchi", "I vestiti sporci"] },
{ frase: "La lingua lunga", corretta: ["Le lingue lunghe"], risposte: ["Le lingue lunghe", "Le lingua lunghe", "Le lingue lunghe", "Le lingue lunghi"] },
{ frase: "Il muro alto", corretta: ["I muri alti"], risposte: ["I muri alti", "Gli muri alti", "I muro alti", "I muri alte"] },
{ frase: "L'uovo cotto", corretta: ["Le uova cotte"], risposte: ["Le uova cotte", "Gli uovi cotti", "I uovi cotti", "Li uovi cotti"] },
{ frase: "La scarpa elegante", corretta: ["Le scarpe eleganti"], risposte: ["Le scarpe eleganti", "Le scarpa eleganti", "I scarpe eleganti", "Le scarpe elegante"] },
{ frase: "L’orologio nuovo", corretta: ["Gli orologi nuovi"], risposte: ["Gli orologi nuovi", "I orologi nuovi", "Gli orologio nuovi", "Li orologi nuovi"] },
{ frase: "La parete verde", corretta: ["Le pareti verdi"], risposte: ["Le pareti verdi", "Le pareti verde", "Le parete verdi", "I pareti verdi"] },
{ frase: "Il soldato valoroso", corretta: ["I soldati valorosi"], risposte: ["I soldati valorosi", "I soldato valorosi", "Gli soldati valorosi", "I soldati valorose"] },
{ frase: "La bottiglia vuota", corretta: ["Le bottiglie vuote"], risposte: ["Le bottiglie vuote", "Le bottiglia vuote", "Le bottiglie vuoti", "I bottiglie vuote"] },
{ frase: "Il compito difficile", corretta: ["I compiti difficili"], risposte: ["I compiti difficili", "I compiti difficile", "Gli compiti difficili", "Li compiti difficili"] },
{ frase: "L’amica simpatica", corretta: ["Le amiche simpatiche"], risposte: ["Le amiche simpatiche", "Le amiche simpatico", "Le amica simpatiche", "Le amiche simpatici"] },
{ frase: "Il fiore colorato", corretta: ["I fiori colorati"], risposte: ["I fiori colorati", "Gli fiori colorati", "I fiore colorati", "Li fiori colorati"] },
{ frase: "La penna nera", corretta: ["Le penne nere"], risposte: ["Le penne nere", "Le penne neri", "Le penna nere", "I penne nere"] },

  { frase: "Lo specchio pulito", corretta: ["Gli specchi puliti"], risposte: ["Gli specchi puliti", "I specchi puliti", "Gli specci puliti", "Gli specchi pulite"] }
]
},
 "Futuro semplice":{
        descrizione: "Completa la frase",
       domande: [
  // --- Verbi regolari (gruppo 1) ---
  { frase: "(Verbo: parlare) Voi domani ___ con il professore.", corretta: ["parlerete"], risposte: ["parlerete", "parlate", "parlavate", "parleranno"] },
  { frase: "(Verbo: studiare) Noi ___ per l’esame la prossima settimana.", corretta: ["studieremo"], risposte: ["studieremo", "abbiamo studiato", "studiamo", "studierete"] },
  { frase: "(Verbo: dormire) Tu ___ meglio in albergo.", corretta: ["dormirai"], risposte: ["dormirai", "dormi", "dormivi", "dormiremo"] },
  { frase: "(Verbo: finire) Loro ___ il lavoro entro domani.", corretta: ["finiranno"], risposte: ["finiranno", "finiscono", "finivano", "finirete"] },
  { frase: "(Verbo: leggere) Io ___ quel libro durante le vacanze.", corretta: ["leggerò"], risposte: ["leggerò", "leggevo", "leggo", "leggeranno"] },
  { frase: "(Verbo: aprire) Marco ___ la finestra più tardi.", corretta: ["aprirà"], risposte: ["aprirà", "apre", "apriva", "apriranno"] },
  { frase: "(Verbo: mangiare) Noi ___ insieme domenica.", corretta: ["mangeremo"], risposte: ["mangeremo", "mangiamo", "mangiavamo", "mangerete"] },
  { frase: "(Verbo: scrivere) Tu ___ una lettera al direttore.", corretta: ["scriverai"], risposte: ["scriverai", "scrivi", "scrivevi", "scriveranno"] },
  { frase: "(Verbo: comprare) Io ___ un regalo per mia madre.", corretta: ["comprerò"], risposte: ["comprerò", "compro", "compravo", "compreranno"] },
  { frase: "(Verbo: lavorare) Voi domani ___ in ufficio tutto il giorno.", corretta: ["lavorerete"], risposte: ["lavorerete", "lavorate", "lavoravate", "lavoreranno"] },

  // --- Verbi regolari (gruppo 2) ---
  { frase: "(Verbo: ascoltare) Io ___ la tua opinione con attenzione.", corretta: ["ascolterò"], risposte: ["ascolterò", "ascolto", "ascoltavo", "ascolteranno"] },
  { frase: "(Verbo: camminare) Noi ___ lungo il fiume domani mattina.", corretta: ["cammineremo"], risposte: ["cammineremo", "camminiamo", "camminavamo", "cammineranno"] },
  { frase: "(Verbo: partire) Voi ___ presto per Roma.", corretta: ["partirete"], risposte: ["partirete", "partite", "partivano", "partiranno"] },
  { frase: "(Verbo: guardare) Tu ___ un bel film stasera.", corretta: ["guarderai"], risposte: ["guarderai", "guardi", "guardavi", "guarderanno"] },
  { frase: "(Verbo: suonare) Lui ___ il pianoforte al concerto.", corretta: ["suonerà"], risposte: ["suonerà", "suona", "suonava", "suoneranno"] },
  { frase: "(Verbo: cucinare) Io ___ per tutti sabato.", corretta: ["cucinerò"], risposte: ["cucinerò", "cucino", "cucinavo", "cucineranno"] },
  { frase: "(Verbo: telefonare) Lei ___ ai suoi genitori più tardi.", corretta: ["telefonerà"], risposte: ["telefonerà", "telefona", "telefonava", "telefoneranno"] },
  { frase: "(Verbo: arrivare) Loro ___ in tempo alla lezione.", corretta: ["arriveranno"], risposte: ["arriveranno", "arrivano", "arrivavano", "arriverete"] },
  { frase: "(Verbo: pulire) Noi ___ tutta la casa domani.", corretta: ["puliremo"], risposte: ["puliremo", "puliamo", "pulivamo", "puliranno"] },
  { frase: "(Verbo: spiegare) Voi ___ tutto ai bambini.", corretta: ["spiegherete"], risposte: ["spiegherete", "spiegate", "spiegavate", "spiegheranno"] },

  // --- Verbi irregolari (gruppo 3) ---
  { frase: "(Verbo: essere) Io ___ felice di vederti.", corretta: ["sarò"], risposte: ["sarò", "sono", "ero", "sarei"] },
  { frase: "(Verbo: avere) Tu ___ una sorpresa domani.", corretta: ["avrai"], risposte: ["avrai", "hai", "avevi", "avresti"] },
  { frase: "(Verbo: andare) Noi ___ in montagna domenica.", corretta: ["andremo"], risposte: ["andremo", "andiamo", "andavamo", "anderemo"] },
  { frase: "(Verbo: venire) Loro ___ alla festa più tardi.", corretta: ["verranno"], risposte: ["verranno", "vengono", "veniranno", "verrebbero"] },
  { frase: "(Verbo: fare) Voi ___ una torta buonissima.", corretta: ["farete"], risposte: ["farete", "fate", "facerete", "faranno"] },
  { frase: "(Verbo: potere) Io ___ aiutarti domani.", corretta: ["potrò"], risposte: ["potrò", "posso", "potevo", "poterò"] },
  { frase: "(Verbo: dovere) Tu ___ studiare di più.", corretta: ["dovrai"], risposte: ["dovrai", "devi", "dovevi", "doverai"] },
  { frase: "(Verbo: volere) Lei ___ venire con noi.", corretta: ["vorrà"], risposte: ["vorrà", "vuole", "voleva", "volerà"] },
  { frase: "(Verbo: sapere) Noi ___ la verità presto.", corretta: ["sapremo"], risposte: ["sapremo", "sappiamo", "sapevamo", "saperemo"] },
  { frase: "(Verbo: vedere) Loro ___ un film interessante.", corretta: ["vedranno"], risposte: ["vedranno", "vedono", "vederanno", "vedrano"] },
  { frase: "(Verbo: rimanere) Tu ___ sorpreso dalla notizia.", corretta: ["rimarrai"], risposte: ["rimarrai", "rimani", "rimanevi", "rimanerai"] },
  { frase: "(Verbo: tenere) Io ___ il segreto per sempre.", corretta: ["terrò"], risposte: ["terrò", "tengo", "tenevo", "tenerò"] },
  { frase: "(Verbo: bere) Lei ___ solo acqua.", corretta: ["berrà"], risposte: ["berrà", "beve", "beveva", "beverà"] },
  { frase: "(Verbo: vivere) Noi ___ in campagna.", corretta: ["vivremo"], risposte: ["vivremo", "viviamo", "vivevamo", "viveremo"] },
  { frase: "(Verbo: cadere) Lui ___ dalla sedia.", corretta: ["cadrà"], risposte: ["cadrà", "cade", "cadeva", "caderà"] },
  { frase: "(Verbo: tradurre) Io ___ il testo in inglese.", corretta: ["tradurrò"], risposte: ["tradurrò", "traduco", "traducevo", "traducerò"] },
  { frase: "(Verbo: produrre) Loro ___ più energia solare.", corretta: ["produrranno"], risposte: ["produrranno", "producono", "producevano", "produceranno"] },
  { frase: "(Verbo: trarre) Tu ___ vantaggio dalla situazione.", corretta: ["trarrai"], risposte: ["trarrai", "trai", "traevi", "trarerai"] },
  { frase: "(Verbo: dire) Voi ___ la verità.", corretta: ["direte"], risposte: ["direte", "dite", "dicevate", "dicerete"] },
  { frase: "(Verbo: uscire) Noi ___ presto.", corretta: ["usciremo"], risposte: ["usciremo", "usciamo", "uscivamo", "uscirete"] }
]
   },

 Pronomi: {
  descrizione: "Completa la seconda frase usando un pronome.",
  domande: [
    {
      frase: "Parlo a Maria e a lei racconto una storia.<br><br>Parlo a Maria e ___ racconto una storia.",
      corretta: ["le"],
      risposte: ["le", "la", "gli", "lo"]
    },
    {
      frase: "Ho tre mele. Mangio 2 di loro.<br><br>Ho tre mele. ___  mangio 2.",
      corretta: ["ne"],
      risposte: ["ne", "le", "li", "gli"]
    },
    {
      frase: "Porto un regalo a Marco e a lui do il regalo con piacere.<br><br>Porto un regalo a Marco e ___ do il regalo con piacere.",
      corretta: ["gli"],
      risposte: ["gli", "lo", "le", "li"]
    },
    {
      frase: "Vuoi pane? Prendo un po’ di pane.<br><br> Vuoi pane?___ prendo un po’ .",
      corretta: ["ne"],
      risposte: ["ne", "lo", "ci", "gli"]
    },
    {
      frase: "Noi siamo al parco. Vedete noi?<br><br>Noi siamo al parco.___ vedete?",
      corretta: ["ci"],
      risposte: ["ci", "li", "le", "ne"]
    },
    {
      frase: "Ti piacciono queste bottiglie? Sì. Porto 2 di queste bottiglie a casa.<br><br>Ti piacciono queste bottiglie?Sì. ___ porto 2 a casa.",
      corretta: ["ne"],
      risposte: ["ne", "le", "ci", "li"]
    },
    {
      frase: "Tu dai a me un libro. Io prendo il libro volentieri.<br><br>Tu  dai a me un libro. Io ___ prendo volentieri.",
      corretta: ["lo"],
      risposte: ["me", "mi", "lo", "gli"]
    },
    {
      frase: "Conosco Paolo. Chiamo Paolo ogni giorno.<br><br>Conosco Paolo. ___ chiamo ogni giorno.",
      corretta: ["lo"],
      risposte: ["lo", "gli", "ci", "ne"]
    },
    {
      frase: "Prendo due  cipolle e lavo le due cipolle.<br><br>Prendo due cipolle e ___ lavo.",
      corretta: ["le"],
      risposte: ["la", "le", "ne", "gli"]
    },
    {
      frase: "Vedo 5 persone. Conosco 2 di loro.<br><br>Vedo 5 persone. ___ conosco 2.",
      corretta: ["ne"],
      risposte: ["ne", "li", "le", "ci"]
    },
    {
      frase: "Prendo la sedia e metto la sedia in cucina.<br><br>Prendo la sedia e ___ metto in cucina.",
      corretta: ["la"],
      risposte: ["la", "le", "ci", "gli"]
    },
    {
      frase: "Spiego  la lezione  e a te do un esercizio.<br><br>Spiego la lezione  e ___ do un esercizio.",
      corretta: ["ti"],
      risposte: ["ti", "lo", "gli", "ci"]
    },
    {
      frase: "Maria ti scrive  una lettera. Tu leggi la lettera.<br><br>Maria ti  scrive una lettera. Tu ___ leggi.",
      corretta: [ "la"],
      risposte: ["ti", "mi", "gli", "la"]
    },
    {
      frase: "Ho una penna. Uso la penna per scrivere.<br><br>Ho una penna. ___ uso per scrivere.",
      corretta: ["la"],
      risposte: ["la", "le", "lo", "ne"]
    },
    {
      frase: "Parlate di scuola? Parliamo spesso di scuola.<br><br>___parliamo spesso .",
      corretta: ["ne"],
      risposte: ["di essa", "di loro", "ne", "la"]
    },
    {
      frase: "Compri il pane e porti il pane a casa?<br><br>Compri il pane e ___ porti a casa?",
      corretta: ["lo"],
      risposte: ["lo", "gli", "ci", "ne"]
    },
    {
      frase: "Prendo due bottiglie e metto le due  bottiglie in frigo.<br><br>Prendo due  bottiglie e ___ metto in frigo.",
      corretta: ["le"],
      risposte: ["la", "lo", "le", "ci"]
    },
    {
      frase: "Tu vedi Anna e saluti Anna.<br><br>Tu vedi Anna e ___ saluti.",
      corretta: ["la"],
      risposte: ["la", "le", "lo", "gli"]
    },
    {
      frase: "Lucia prepara gli involtini  e poi cuoce gli involtini.<br><br>Lucia prepara gli involtini e poi ___ cuoce.",
      corretta: ["li"],
      risposte: ["la", "li", "lo", "gli"]
    },
    {
      frase: "Mario racconta una novità a noi.<br><br>Mario ___ racconta una novità..",
      corretta: ["ci"],
      risposte: ["ci", "vi", "gli", "le"]
    },
    {
      frase: "Guardo un film e poi racconto il film a Marco.<br><br>Guardo un film e poi ___ racconto a Marco.",
      corretta: ["lo"],
      risposte: ["lo", "gli", "le", "ne"]
    },
    {
      frase: "Marta e io siamo a casa. Carlo chiama Marta e me.<br><br>Marta e io siamo a casa.Carlo ___ chiama.",
      corretta: ["ci"],
      risposte: ["ci", "vi", "li", "ne"]
    },
    {
      frase: "Conosco Anna e a lei telefono spesso.<br><br>Conosco Anna e ___ telefono spesso.",
      corretta: ["le"],
      risposte: ["le", "la", "gli", "ci"]
    },
    {
      frase: "Tu mi porti i piatti sporchi. Io lavo i piatti sporchi.<br><br>Tu mi porti i piatti sporchi. Io ___ lavo.",
      corretta: ["li"],
      risposte: ["li", "le", "lo", "gli"]
    },
    {
      frase: "Scrivo una lettera a te e Lucia e a voi mando un saluto.<br><br>Scrivo una lettera a te e Lucia e ___ mando un saluto.",
      corretta: ["vi"],
      risposte: ["le", "vi", "gli", "ci"]
    },
    {
  frase: "Abbiamo comprato i libri e leggiamo i libri.<br><br>Abbiamo comprato i libri e ___ leggiamo.",
  corretta: ["li"],
  risposte: ["li", "le", "lo", "gli"]
},
{
  frase: "Mando un messaggio a te.<br><br>___ mando un messaggio.",
  corretta: ["ti"],
  risposte: ["ti", "lo", "gli", "ci"]
},
{
  frase: "Voglio un po’ di torta. Prendo un po’ di torta.<br><br>___ prendo un po'.",
  corretta: ["ne"],
  risposte: ["ne", "la", "ci", "gli"]
},
{
  frase: "Portiamo i bicchieri a Carlo e a lui diamo anche i piatti.<br><br>Portiamo i bicchieri a Carlo e ___ diamo anche i piatti.",
  corretta: ["gli"],
  risposte: ["gli", "lo", "li", "ci"]
},
{
  frase: "Conosco quelle ragazze.  Ora saluto quelle ragazze.<br><br>Conosco quelle ragazze? Ora  ___ saluto.",
  corretta: ["le"],
  risposte: ["le", "li", "la", "gli"]
},
{
  frase: "Mi serve del latte. Compro un po’ di latte.<br><br>Mi serve del latte. ___ compro un po’.",
  corretta: ["ne"],
  risposte: ["ne", "lo", "ci", "gli"]
},
{
  frase: "Abbiamo un fratello. Parliamo spesso di nostro fratello.<br><br>Abbiamo un fratello. ___ parliamo spesso.",
  corretta: ["ne"],
  risposte: ["ne", "gli", "lo", "ci"]
},
{
  frase: "Hai visto il film? Sì, ho visto il film.<br><br>Hai visto il film? Sì, ___ ho visto.",
  corretta: ["l'"],
  risposte: ["l'", "gli", "ne", "ci"]
},
{
  frase: "Dico la verità a voi.<br><br>___ dico la verità.",
  corretta: ["vi"],
  risposte: ["vi", "ci", "gli", "le"]
},
{
  frase: "Invito te e Paolo alla festa.<br><br>___ invito alla festa.",
  corretta: ["vi"],
  risposte: ["vi", "ci", "li", "le"]
},
{
  frase: "Ricevo molte lettere. Leggo tutte le lettere.<br><br>Ricevo molte lettere. ___ leggo tutte.",
  corretta: ["le"],
  risposte: ["le", "li", "la", "gli"]
},
{
  frase: "Spedisco un regalo a mia sorella.<br><br>___ spedisco un regalo.",
  corretta: ["le"],
  risposte: ["le", "gli", "la", "ci"]
},
{
  frase: "Ho dei panini nel  frigo. Prendo due panini dal frigo<br><br>Ho dei panini nel  frigo.__ prendo due .",
  corretta: ["ne"],
  risposte: ["ne", "li", "lo", "gli"]
},
{
  frase: "Scrivete a me una mail?<br><br>___ scrivete una mail?",
  corretta: ["mi"],
  risposte: ["mi", "vi", "ti", "gli"]
},
{
  frase: "Diciamo la verità a loro.<br><br>Diciamo ___  la verità.",
  corretta: ["gli"],
  risposte: ["gli", "le", "li", "ci"]
},
{
  frase: "Lucia mi ha regalato un libro. Io leggo il libro.<br><br>Lucia mi ha regalato un libro. Io ___ leggo.",
  corretta: ["lo"],
  risposte: ["lo", "gli", "le", "li"]
},
{
  frase: "Compro i quaderni per voi.<br><br>___ compro i quaderni.",
  corretta: ["vi"],
  risposte: ["vi", "ci", "gli", "le"]
},
{
  frase: "Parli spesso di quella storia? Sì, parlo spesso di quella storia.<br><br>Parli spesso di quella storia? Sì, ___parlo spesso.",
  corretta: ["ne"],
  risposte: ["ne", "lo", "gli", "la"]
},
{
  frase: "Chiamiamo la professoressa? Sì, chiamiamo subito la professoressa.<br><br> Chiamiamo la professoressa? Sì, ___ chiamiamo subito.",
  corretta: ["la"],
  risposte: ["la", "le", "gli", "ci"]
},
{
  frase: "Invito Marco e Anna alla cena.<br><br>___ invito alla cena.",
  corretta: ["li"],
  risposte: ["li", "le", "gli", "vi"]
}

  ]
}

  };
  
  

